server:
  port: 8081

spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:postgresql://${DBHOST:localhost}:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:8083


