server:
  port: 8080

spring:
  application:
      name: PRODUCT-SERVICE
  datasource:
    url: jdbc:postgresql://${DBHOST:localhost}:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update

      
eureka:
   instance:
     preferIpAddress: true
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      

